local_costmap:
  global_frame: odom
  robot_base_frame: robot_base
  update_frequency: 2.5
  publish_frequency: 2.5
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05